name: Monitor Google Sheet

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install gspread pandas google-auth

      - name: Run monitoring script
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}  # Pass the secret as an environment variable
        run: |
          python monitor_latest_entry.py
